### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by JacobWise1**
Added a note on install grunt to the file path in order to ease installation and use of the maps and added a fourth step to the grunt installation instructions

### CODE REVIEW

**Comment by cengique** [comment]
@JacobWise1 you should merge this pull request yourself as this is your own repository.

**Comment by jpmanz** [comment]
I don't understand
@cengique

**Comment by cengique** [comment]
@jpmanz slick on "Merge this pull request". And stop creating these.

**Comment by cengique** [comment]
Contributing file already has grunt instructions

**Pull request closed without merging**
